"""secure_owner_and_media

Revision ID: 03a6ff552596
Revises: 06cbb2bf0b3e
Create Date: 2026-09-01 01:47:13.217625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03a6ff552596'
down_revision: Union[str, Sequence[str], None] = '06cbb2bf0b3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('source_kind', sa.String(length=8), server_default='text', nullable=False))
    op.add_column('users', sa.Column('has_usable_password', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # Rename unique constraints to naming_convention (u_pfx).
    op.drop_constraint('users_discord_id_key', 'users', type_='unique')
    op.drop_constraint('users_telegram_id_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_index('one_owner', 'users', ['role'], unique=True, postgresql_where=sa.text("role = 'owner'"))
    op.create_unique_constraint('uq_users_discord_id', 'users', ['discord_id'])
    op.create_unique_constraint('uq_users_telegram_id', 'users', ['telegram_id'])
    op.create_unique_constraint('uq_users_username', 'users', ['username'])
    op.create_check_constraint('ck_users_role_valid', 'users', "role IN ('owner', 'user')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_users_role_valid', 'users', type_='check')
    op.drop_constraint('uq_users_username', 'users', type_='unique')
    op.drop_constraint('uq_users_telegram_id', 'users', type_='unique')
    op.drop_constraint('uq_users_discord_id', 'users', type_='unique')
    op.drop_index('one_owner', table_name='users', postgresql_where=sa.text("role = 'owner'"))
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_telegram_id_key', 'users', ['telegram_id'])
    op.create_unique_constraint('users_discord_id_key', 'users', ['discord_id'])
    op.drop_column('users', 'has_usable_password')
    op.drop_column('messages', 'source_kind')
    # ### end Alembic commands ###
