"""hard facts uniqueness

Revision ID: 06cbb2bf0b3e
Revises: abbdbc96f127
Create Date: 2026-08-26 02:35:56.583682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06cbb2bf0b3e'
down_revision: Union[str, Sequence[str], None] = 'abbdbc96f127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_hard_facts_identity', 'hard_facts', ['user_id', 'category', 'key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_hard_facts_identity', 'hard_facts', type_='unique')
    # ### end Alembic commands ###
