"""fk ondelete cascade

Revision ID: abbdbc96f127
Revises: eda380bd303f
Create Date: 2026-08-24 02:51:28.653382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abbdbc96f127'
down_revision: Union[str, Sequence[str], None] = 'eda380bd303f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('audit_logs_user_id_fkey'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('auth_tokens_user_id_fkey'), 'auth_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'auth_tokens', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('hard_facts_user_id_fkey'), 'hard_facts', type_='foreignkey')
    op.create_foreign_key(None, 'hard_facts', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('messages_user_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_user_id_fkey'), 'messages', 'users', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'hard_facts', type_='foreignkey')
    op.create_foreign_key(op.f('hard_facts_user_id_fkey'), 'hard_facts', 'users', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'auth_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('auth_tokens_user_id_fkey'), 'auth_tokens', 'users', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('audit_logs_user_id_fkey'), 'audit_logs', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
